#!/bin/bash
find . -type f -iname '*.gif' | while read file
do
    name=`echo $file | cut -f 1 -d '.'`
    size=`ls -l --sort=size $file | awk '{ print $5 }'`
    echo "$name $size"
done | sort -k 2 -t ' ' | cut -f 1 -d ' '

